In [1]:
import pandas as pd
import numpy as np 

In [2]:
# load in the current dataset 
dataset = pd.read_csv("predictingCSectionsInWomanData.csv", header=0)

# drop the unnecessary rows and columns 
dataset.drop(dataset.columns[[18, 19, 20, 21]], axis=1, inplace=True)
dataset.drop(dataset.index[[302, 303, 304,305, 306]], inplace=True)

dataset

Age  Weight  Height     BMI  nParity  Cesarean  dPreg  nPat  Bishop  \
0    24.0    97.0    1.69  33.962      0.0       0.0  289.0   1.0     6.0   
1    18.0    61.0    1.65  22.406      0.0       0.0  271.0   2.0     3.0   
2    33.0    95.0    1.71  32.489      1.0       0.0  260.0   2.0     5.0   
3    35.0    77.0    1.63  28.981      1.0       0.0  288.0   0.0     1.0   
4    27.0    88.0    1.49  39.638      1.0       0.0  288.0   1.0     3.0   
..    ...     ...     ...     ...      ...       ...    ...   ...     ...   
297  40.0    92.0    1.75  30.041      1.0       0.0  273.0   1.0     1.0   
298  33.0    63.0    1.59  24.920      0.0       0.0  254.0   0.0     4.0   
299  27.0    87.0    1.54  36.684      0.0       0.0  266.0   2.0     1.0   
300  22.0    88.0    1.55  36.629      0.0       0.0  276.0   0.0     2.0   
301  37.0    82.0    1.56  33.695      3.0       0.0  230.0   1.0     3.0   

     Reason  Met  indTime  indDay  Epidural  Oxy   RM  dilRM mDelivery  
0      17.0  4.0     11.8     2.0       1.0  0.0  2.0    5.0  Delivery  
1      21.0  4.0     15.0     2.0       1.0  0.0  1.0    1.0  Delivery  
2       9.0  4.0     11.2     2.0       1.0  0.0  2.0    8.0  Delivery  
3      17.0  3.0     12.5     4.0       1.0  0.0  1.0    4.0  Delivery  
4      17.0  3.0     17.0     5.0       1.0  0.0  2.0   10.0  Delivery  
..      ...  ...      ...     ...       ...  ...  ...    ...       ...  
297    23.0  1.0      8.7     6.0       0.0  0.0  0.0    0.0  Cesarean  
298     9.0  2.0      2.5     3.0       1.0  1.0  2.0    7.0  Delivery  
299     9.0  1.0     16.5     4.0       0.0  1.0  2.0    5.0  Delivery  
300    11.0  1.0     11.7     5.0       1.0  1.0  2.0    5.0  Delivery  
301     8.0  3.0     19.8     2.0       0.0  0.0  0.0    0.0  Cesarean  

[302 rows x 18 columns]

In [3]:
# converting the Delivery to numerical values 
# 0 --> Delivery 
# 1 --> Cesarean 

dataset = dataset.replace({"Delivery": 0, "Cesarean":1})
features = list(dataset.columns)

print(features)

dataset

['Age', 'Weight', 'Height', 'BMI', 'nParity', 'Cesarean', 'dPreg', 'nPat', 'Bishop', 'Reason', 'Met', 'indTime', 'indDay', 'Epidural', 'Oxy', 'RM', 'dilRM', 'mDelivery']


Age  Weight  Height     BMI  nParity  Cesarean  dPreg  nPat  Bishop  \
0    24.0    97.0    1.69  33.962      0.0       0.0  289.0   1.0     6.0   
1    18.0    61.0    1.65  22.406      0.0       0.0  271.0   2.0     3.0   
2    33.0    95.0    1.71  32.489      1.0       0.0  260.0   2.0     5.0   
3    35.0    77.0    1.63  28.981      1.0       0.0  288.0   0.0     1.0   
4    27.0    88.0    1.49  39.638      1.0       0.0  288.0   1.0     3.0   
..    ...     ...     ...     ...      ...       ...    ...   ...     ...   
297  40.0    92.0    1.75  30.041      1.0       0.0  273.0   1.0     1.0   
298  33.0    63.0    1.59  24.920      0.0       0.0  254.0   0.0     4.0   
299  27.0    87.0    1.54  36.684      0.0       0.0  266.0   2.0     1.0   
300  22.0    88.0    1.55  36.629      0.0       0.0  276.0   0.0     2.0   
301  37.0    82.0    1.56  33.695      3.0       0.0  230.0   1.0     3.0   

     Reason  Met  indTime  indDay  Epidural  Oxy   RM  dilRM  mDelivery  
0      17.0  4.0     11.8     2.0       1.0  0.0  2.0    5.0          0  
1      21.0  4.0     15.0     2.0       1.0  0.0  1.0    1.0          0  
2       9.0  4.0     11.2     2.0       1.0  0.0  2.0    8.0          0  
3      17.0  3.0     12.5     4.0       1.0  0.0  1.0    4.0          0  
4      17.0  3.0     17.0     5.0       1.0  0.0  2.0   10.0          0  
..      ...  ...      ...     ...       ...  ...  ...    ...        ...  
297    23.0  1.0      8.7     6.0       0.0  0.0  0.0    0.0          1  
298     9.0  2.0      2.5     3.0       1.0  1.0  2.0    7.0          0  
299     9.0  1.0     16.5     4.0       0.0  1.0  2.0    5.0          0  
300    11.0  1.0     11.7     5.0       1.0  1.0  2.0    5.0          0  
301     8.0  3.0     19.8     2.0       0.0  0.0  0.0    0.0          1  

[302 rows x 18 columns]

In [4]:
# creating the first decision tree 

from sklearn import tree 

# convert dataset to numpy for easier usse
data = dataset.to_numpy()

X = data[:,0:17]
y = data[:,17:18]

# showing what is in the X array 
# X

In [5]:
# showing what is in the y array or the labels 
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],

In [6]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
selected = SelectKBest(chi2, k=3)
x_new = selected.fit_transform(X, y)

In [7]:
filter = selected.get_support()
print("All features: ")
print(features)
print("Selected best 4: ")
count = 0
for filtered in filter:
    if filtered == True:
        print(features[count])
    count += 1

All features: 
['Age', 'Weight', 'Height', 'BMI', 'nParity', 'Cesarean', 'dPreg', 'nPat', 'Bishop', 'Reason', 'Met', 'indTime', 'indDay', 'Epidural', 'Oxy', 'RM', 'dilRM', 'mDelivery']
Selected best 4: 
Epidural
RM
dilRM


In [8]:
from sklearn.model_selection import train_test_split

# creating the testing and training datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True)

# creating the decision tree and fitting the train data to the decision tree

decision_tree = tree.DecisionTreeClassifier()
decision_tree = decision_tree.fit(X_train, y_train)

In [9]:
import graphviz
dot_data = tree.export_graphviz(decision_tree, out_file=None)
graph = graphviz.Source(dot_data)
graph.render("Predicting Delivery Method")

'Predicting Delivery Method.pdf'

In [10]:
# predicting the values given the current decision tree
predicted_values = decision_tree.predict(X_test)
predicted_values


array([0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0.,
       1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 1., 1., 0., 0.])

In [11]:
from sklearn.metrics import accuracy_score
accuracyScore = accuracy_score(y_test,predicted_values)

print("The accuracy score for this data is: " + str(accuracyScore), "%")

The accuracy score for this data is: 0.7692307692307693 %


In [335]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
selected_tree = SelectKBest(chi2, k=17)
x_new_tree = selected_tree.fit_transform(X, y)

In [336]:
filter_tree = selected_tree.get_support()
print("All features: ")
print(features)
print("Selected best 4: ")
count = 0
for filtered in filter_tree:
    if filtered == True:
        print(features[count])
    count += 1

All features: 
['Age', 'Weight', 'Height', 'BMI', 'nParity', 'Cesarean', 'dPreg', 'nPat', 'Bishop', 'Reason', 'Met', 'indTime', 'indDay', 'Epidural', 'Oxy', 'RM', 'dilRM', 'mDelivery']
Selected best 4: 
Age
Weight
Height
BMI
nParity
Cesarean
dPreg
nPat
Bishop
Reason
Met
indTime
indDay
Epidural
Oxy
RM
dilRM


In [337]:
from sklearn.model_selection import train_test_split

# creating the testing and training datasets
X_train_tree, X_test_tree, y_train_tree, y_test_tree = train_test_split(x_new_tree, y, test_size=0.3, shuffle=True)


In [338]:
from sklearn.ensemble import RandomForestClassifier 
from sklearn.datasets import make_classification

clf = RandomForestClassifier(max_depth=2, random_state=0)
forest = clf.fit(X_train_tree, y_train_tree.ravel())

In [339]:
predicted_tree = forest.predict(X_test_tree)
predicted_tree

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [340]:
accuracyScore = accuracy_score(y_test_tree ,predicted_tree)

print("The accuracy score for this data is: " + str(accuracyScore), "%")

The accuracy score for this data is: 0.8131868131868132 %
